### ISSUE TITLE
InteractiveChat kick-all with shulker

### ISSUE THREAD

**Issue by Projecki** [LOOHP/InteractiveChat#221]
When using this shulker, which has relatively light NBT data, many players are kicked.

Presumably the kicked players are using 1.20.6? Unconfirmed. But only some players get kicked, and the ones that are kicked are kicked consistently.

https://pastebin.com/0FQCjuEp spigot logs
https://mclo.gs/soxEBzl velocity logs
seeking client logs from an affected user, will update if I get them

![image](https://github.com/LOOHP/InteractiveChat/assets/65093423/116b32fa-c398-4615-9e55-1863c07ce953)

Schem file of the shulker in question:
https://drive.google.com/file/d/1RtcFYCQKA9qSnIHPO5TcSPN8poAxkHLW/view?usp=sharing

**Comment by LOOHP** [comment]
Try **decreasing** `ItemTagMaxLength` on backend servers' IC config by something like 2000 each time. See whether at some point this issue stops appearing.

**Comment by Projecki** [comment]
Okay

Here are client logs, affects all 1.21 users: https://pastebin.com/LZaeyhZE

The bug is fixed at ItemTagMaxLength: 5000 & below

what are the implications of lowering this number?

**Comment by LOOHP** [comment]
It just removes the item data if it is too long in the hover item data. Players can still see the item content when they click on it.
